// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIPhsU_3SfwJeNmYNBTeW1hIuPn77HsPM',
    appId: '1:645768039666:web:330c32398d4d66c937546b',
    messagingSenderId: '645768039666',
    projectId: 'talk-to-quran',
    authDomain: 'talk-to-quran.firebaseapp.com',
    storageBucket: 'talk-to-quran.firebasestorage.app',
    measurementId: 'G-GB63HHZHF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAapUrgU_Efx3UBG0ukqHn6vLZJaKiOfRo',
    appId: '1:645768039666:android:bdaa429b58a2028337546b',
    messagingSenderId: '645768039666',
    projectId: 'talk-to-quran',
    storageBucket: 'talk-to-quran.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB38SoQo4a20ArF8H9Bv-ExyhsTbRKgVEc',
    appId: '1:645768039666:ios:2b0625818ddadac337546b',
    messagingSenderId: '645768039666',
    projectId: 'talk-to-quran',
    storageBucket: 'talk-to-quran.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB38SoQo4a20ArF8H9Bv-ExyhsTbRKgVEc',
    appId: '1:645768039666:ios:2b0625818ddadac337546b',
    messagingSenderId: '645768039666',
    projectId: 'talk-to-quran',
    storageBucket: 'talk-to-quran.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIPhsU_3SfwJeNmYNBTeW1hIuPn77HsPM',
    appId: '1:645768039666:web:585a1b620e0c003e37546b',
    messagingSenderId: '645768039666',
    projectId: 'talk-to-quran',
    authDomain: 'talk-to-quran.firebaseapp.com',
    storageBucket: 'talk-to-quran.firebasestorage.app',
    measurementId: 'G-0B278MXSRZ',
  );
}
